# Generated by Django 3.2.13 on 2022-05-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0010_auto_20200508_1851'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='region',
            name='country',
        ),
        migrations.RemoveField(
            model_name='subregion',
            name='country',
        ),
        migrations.RemoveField(
            model_name='subregion',
            name='region',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='SubRegion',
        ),
    ]
